### ISSUE TITLE
Enable private link for Azure Monitor in Workspaces

### ISSUE THREAD

**Issue by tompaana** [microsoft/AzureTRE#1057]
Builds upon #742 

The AMPLS (defined in `/templates/core/terraform/azure-monitor/azure-monitor.tf`) *should* be able to support the Application Insights instances in Workspaces too.

Otherwise traffic to app insights is blocked by the firewall and creates many Deny logs.

## Acceptance criteria

- [ ] Prototype the use of AMPLS for Workspace App Insights instances in Portal and verify that the logs sent by the Workspace/Workspace Service get through (note: may require new storage to be linked with App Insights, see other task below)
    ![Adding resource to AMPLS](https://user-images.githubusercontent.com/1629215/138292310-88526358-8958-4507-a63a-637cd04723c8.png)
- [ ] If the aforementioned approach was successful, update the Workspace (Service) installation/uninstallation pipelines to add/remove App Insights and other Azure Monitor resources deployed by the Workspace (Service) to/from the AMPLS
    - The resource ID of AMPLS need to be provided as output by `tre-deploy` target - OR - provide it directly in Terraform to Resource Processor as an env variable to be then injected to Porter installations requiring it?
- [ ] App Insights behind Private Link requires a separately created, linked storage, see [Configure Bring Your Own Storage (BYOS) for Application Insights](https://docs.microsoft.com/azure/azure-monitor/app/profiler-bring-your-own-storage)
    - Use `/templates/core/terraform/azure-monitor/azure-monitor.tf` as reference

**Comment by martinpeck** [comment]
When picking this task up, the first thing to do is to start a design discussion (including @marrobi and others in Core TRE Dev) to determine the best way to approach this.

**Comment by stuartleeks** [comment]
Assumption: the desire is to have a separate App Insights instance per workspace (to preserve workspace isolation)

To enable connecting to Azure Monitor from within a workspace VNET (where traffic is restricted), we need to have an Azure Monitor Private Link Scope (AMPLS) that is connected to a Private Endpoint within the VNET.

An AMPLS can be connected to multiple Private Endpoints and multiple Azure Monitor resources, but [an AMPLS can only connect to up to 10 Private Endpoints](https://docs.microsoft.com/en-us/azure/azure-monitor/logs/private-link-design#consider-ampls-limits) so the suggestion is to deploy an AMPLS per workspace for simplicity.

Because there are some shared endpoints (i.e. not resource-specific), a [single AMPLS should be used for all VNETs that share the same DNS](https://docs.microsoft.com/en-us/azure/azure-monitor/logs/private-link-security#azure-monitor-private-links-rely-on-your-dns). Currently, we have separate VNETs for each workspace but each VNET is linked to the same, single private DNS Zone for Azure Monitor/App Insights. To enable an AMPLS per workspace, we need to update the private DNS Zones for Azure Monitor so that the existing zones are just used for the core VNET and deploy separate zones for each workspace.

Summary of proposed changes
- Update the existing Azure Monitor DNS zones to only be used for the core VNET (i.e. don't link to workspace VNETs)
- For workspaces, add
   - DNS zones for Azure Monitor and link to the VNET
   -  Azure Monitor Private Endpoints 
   - An AMPLS connected to the Private Endpoint

**Comment by ross-p-smith** [comment]
You mention App Insights - does this include Log Analytics too? For instance, should App Insights forward it's Diagnostic settings toa  Log Analytics Workspace?

**Comment by marrobi** [comment]
@stuartleeks did you manage to confirm this worked from a logging perspective.

We also need to get issues created for any workspace services that use app insights as they will need to be amended.

**Comment by stuartleeks** [comment]
@marrobi - I'm in the middle of that currently (fitting it around other work)

**Comment by stuartleeks** [comment]
Closing as @tamirkamara implemented the remainder of this for guacamole service
