### ISSUE TITLE
Implement fastapi-azure-auth package rather than custom auth code

### ISSUE THREAD

**Issue by marrobi** [microsoft/AzureTRE#1074]
## Description

As a TRE Developer
I want to use an existing library for authentication
So that we have less custom auth code

## Acceptance criteria

- [ ] Extend https://intility.github.io/fastapi-azure-auth/ and replace custom code in AAD Authenticator

**Comment by marrobi** [comment]
Also look at https://github.com/425Show/fastapi_microsoft_identity

**Comment by tamirkamara** [comment]
Currently @LizaShak is evaluating options

**Comment by LizaShak** [comment]
The FastAPI-Azure-Auth evaluation summary:
1. It can replace the authentication code where we check the signature manually and etc.. 
2. It is not meant to work with multiple client ids (we do have it since we have tokens coming from ui and workspaces)
3. Doesn't have an authorization decoration option

**Comment by tamirkamara** [comment]
So @LizaShak, does it make sense to go ahead with this task or not?

**Comment by LizaShak** [comment]
@tamirkamara I personally think it is not a good for us since it is not meant to work with multiple client ids as we do. On top it doesn't eliminate all the authorization code. We also didn't find any other lib that does it (asked also on the security channel). What I think we should do is replace the code that does all the manual signature validation (part of it is the public and private key validation). But I don't think that was the goal of this task... Maybe I'd open a separate task for that?

**Comment by marrobi** [comment]
@LizaShak is there no way to override this call (in this example) - https://github.com/Intility/fastapi-azure-auth/blob/749ccb1f87f7fe1e32017049497609757b8bb76e/demo_project/api/dependencies.py#L20 - so that it uses the workspace ID to get the appropriate `client_id` as per https://github.com/microsoft/AzureTRE/blob/50e5763eabd0a5dcc130d27095c3a7c528b1471c/api_app/services/aad_authentication.py#L60 ?

I'm keen to have us maintain as little auth code as possible.

**Comment by LizaShak** [comment]
@marrobi closing this issue as we agreed yesterday. Creating a new one to spike and handle the token validation,
