### ISSUE TITLE
Building InnerEye Workspace Fails with NoPublicIP Error on ML Compute Cluster

### ISSUE THREAD

**Issue by dram1964** [microsoft/AzureTRE#1083]
**Deployment of InnerEye Workspace Fails from API because of Public IP Address Setting on Compute Cluster**

Deploying InnerEye Workspace via API fails during the build of machine learning compute workspaces

**Error Message**
code: PropertyNotAllowed
message: Cluster without public IP is not supported in the compute region. Please refer to this documentation for the regions support No Public IP cluster https://docs.microsoft.com/azure/batch/batch-pool-no-public-ip-address

**Steps to reproduce**

1.     Deploy TRE
2.     Publish tre-workspace-innereye using porter build and publish_register_bundle.sh script
3.     Deploy InnerEye Workspace via POST to /api/workspaces
4.     Check Deployment Status via GET /api/workspacess/{workspace_id}

**Temporary Fix**
Set parameter EnableNodePublicIp to 'true' in: templates > workspace_services > azureml > user_resources > aml_compute > terraform > deploypl_compute_instance.json

**Comment by marrobi** [comment]
@dram1964 this relates to #1081, that's why those restrictions were there - although did need removing as were outdated.

Before enabling public IP on the compute, you should to understand if enabling a public IP on compute impacts your IG policies or not.

We could add an option of enabling public IP on Azure ML, but is not something we can fix. Will be a case of manually overriding as you have done for now.

Will close this as isn't something we can fix in the Azure TRE project - need to wait on region availability. Useful info for others so thanks for reporting, and hope other regions are enabled soon.

cc @ktakeda1 @deniscep
