### ISSUE TITLE
Add source control support

### ISSUE THREAD

**Issue by daltskin** [microsoft/AzureTRE#1228]
**Describe the solution you'd like**
As a researcher I want to be able to use source control within a workspace service

**Additional context**
- Ability to create repositories
- Create branches
- Commit code

- [x] #1299

**Comment by yorkecp** [comment]
The basic requirements for most researches in my experience are just an ability to have remote repositories hosted within the workspace so that small scale code sharing can occur but more importantly version history is preserved.

As described the requirements are really just to be able to create repositories and push code to main and other branches.

Minimal implementation will make any information governance questions easier and have lower operating costs.

**Comment by marrobi** [comment]
I suggest a workspace service making use of the work done in the Gitea shared service bundle (part of #1177 )

**Comment by marrobi** [comment]
An alternate option was suggested, where we have a proxy in front of a shared Git  provision restricting access to each Git organization by workspace IP range. I think this might be something to look at longer term.

**Comment by yorkecp** [comment]
Being able to have git organisations per workspace makes great sense and then being able to have the Git provision as part of the TRE Core would mitigate the cost per workspace issue an additional instance in each workspace brings. That seems like a good longer term solution.

**Comment by daltskin** [comment]
@yorkecp for initial implementation - user story #1299 created

**Comment by mjbonifa** [comment]
Just repeating a discussion here from SDF TRE:

We'd ideally want
* Gitlab with support for CI/CD pipelines within a workspace
* Ability to export repos from a workspace in a similar way to the airlock process? There are many possible ways of achieving that to be discussed but code is an artefact for export.

**Comment by marrobi** [comment]
Closing this as source control complete. 

Acknowledge secure ML Ops needs a solution. Will create a separate issue for GitLab, or might be covered as part of https://github.com/microsoft/AzureTRE/issues/1502 albeit with licensing implications.
