### ISSUE TITLE
Documentation : remove return lines from all command we have to copy

### ISSUE THREAD

**Issue by chboudry** [microsoft/AzureTRE#1398]
**Is your feature request related to a problem? Please describe.**
In the documentation, for the tutorial, there are a lot of commands to copy
Most of the line have to be edited before running them...
...But all of them include a return line, which mean it will be run as soon as they are pasted.

**Describe the solution you'd like**
Remove all return lines from the commands.

**Comment by chboudry** [comment]
@marrobi can you assigned this one to me ?

**Comment by martinpeck** [comment]
I'm going to close this as "won't fix"

I've done a little investigation. The markup and code associated with the "copy to clipboard" feature of the docs is all part of MkDocs, the Material theme, and PyMDown extensions, and superfences. 

Without turning code styling off entirely, this is hard to fix.

I also don't believe we can write the docs any differently...

- one line code snippets have the newline added by the above set of components
- two line code snippets will, obviously, include newlines

Recommend copying into a text editor, rather than direct into the terminal, when using snippets from the docs.
