### ISSUE TITLE
Validate API requests against workspaceTemplate parameters

### ISSUE THREAD

**Issue by christoferlof** [microsoft/AzureTRE#142]
## Description

As a TRE workspace owner
I want to have the *new workspace service* request parameters validated
So that I can create new workspace services with confidence, getting quick feedback on whether my request will be accepted or not.

## Acceptance criteria

- [ ] workspaceTemplate name and version are validated
- [ ] Request parameters validated against the parameter definitions on the specified workspaceTemplate.
- [ ] In case of validation errors, HTTP 400 Bad Request is returned with a message describing which parameter(s) that failed the validation.

## Examples

Given that a workspace bundle is registered with the following resourceSpec:

```json
{
    "name": "tre-workspace-vanilla",
    "version": "0.1.0",
    "parameters" : [
    {
        "name": "location",
        "type": "string",
        "default": null,
        "applyTo": "All Actions",
        "description": "Azure location (region) to deploy to",
        "required": true
      },
      {
        "name": "address_space",
        "type": "string",
        "default": "10.2.1.0/24",
        "applyTo": "All Actions",
        "description": "VNet address space for the workspace services",
        "required": false
      }
    ]
}
```
When a request is made to `/workspaces` to create a new workspace with the below request body:

```json
{
    "resourceSpec": {
       "name": "tre-workspace-vanilla",
       "version": "0.1.0"
    },
    "parameters": {
       "address_space": "10.3.1.0/24"
    },
    "name": "my first workspace"
}
```

Then a HTTP 400 Bad Request is returned with a message saying that the parameter "location" is missing or incorrect:

```http
HTTP 400 Bad Request

{
    "resourceSpec": {
       "name": "tre-workspace-vanilla",
       "version": "0.1.0"
    },
    "validationErrors": [
        "Parameter name `location` is required"
    ]
}
```

**Comment by christoferlof** [comment]
As part of implementing this, let's think about how to add more granular validation rules, like allowed locations etc.

**Comment by TessFerrandez** [comment]
Me and @marrobi have started thinking about this a little bit - we may extract the json schema on the porter bundle and validate directly against it with pydantic (maybe) -- but we should create anther story with a deeper investigation there after this basic validation

**Comment by marrobi** [comment]
@TessFerrandez I've done some research around this, and believe storing a standards compliant JSON Schema (as with a past implementation) within the Resource Template rather than a set of Porter parameters would be a good solution. 

That validation can be done by a package such as https://python-jsonschema.readthedocs.io/en/stable/ - we can add our own checks for custom data types using: https://python-jsonschema.readthedocs.io/en/stable/validate/#jsonschema.FormatChecker.checks

Then when a UI requests a Workspace Template they get the schema, and can generate a UI using libraries such as https://jsonforms.io/ .

Let me know if want to talk further.
