### ISSUE TITLE
Allow for secrets when creating resources

### ISSUE THREAD

**Issue by ross-p-smith** [microsoft/AzureTRE#1922]
## Description

As a TRE Administrator
I want the API to accept secrets when creating resources
So that I can add them to a secret store

## Acceptance criteria

- [x] #2147

**Comment by ross-p-smith** [comment]
If you look at the test_create_guacamole_service_into_base_workspace test, and ultimately when you create a workspace; you have to pass in the Workspace_Client_Id/Secret. This gets stored inside the "Resource" document in cosmos and is ultimately passed to a bundle. Now we don't want to see that secret in the document, but it needs to get passed to Terraform for it to end up in the Workspace KeyVault

**Comment by tanya-borisova** [comment]
We had a discussion this morning during standup regarding this ticket. Some notes from that discussion are below.

Consider creating a resource which accepts secret as an input. Currently, the flow works like this:
User issues a request to API with a secret. This is persists in Cosmos currently. A message with the secret is also sent to Service Bus, which gets read by Resource Processor. Resource Processor passes that secret and installs the resource bundle. In terraform configuration of the bundle, the secret is then saved into a keyvault. For example, when we install Guacamole into workspace, it then references a secret already stored in the keyvault. 

There are broadly two ways to go about this:

1) @tamirkamara's suggestion: Not persisting secret in Cosmos. This means we don't have to deal with encrypting and decrypting of the secret. However the update flow is unclear. When updating a resource, the same set of input parameters is required as when installing a resource, which means that Resource Processor will need to provide a secret, which at this point it does not have access to, unless a special solution is implemented for this. 

2) @ross-p-smith's suggestion: Persisting secret in Cosmos. This means we need to encrypt secret in API when it is stored, using some sort of Primary Key which will be stored in Core Keyvault, and decrypt it in Resource Processor before sending it to the bundle during installs and updates. This solves problem of resource update but requires encrypting and decrypting secrets in Cosmos, which now need to be treated as a special value type. 

A consideration to keep in mind is that secrets also need to be rotated, both the resource secrets and Primary Key (if solution 2 is used).

**Comment by damoodamoo** [comment]
Some thoughts on each...

1) The install parameters _can_ be different to the upgrade parameters at the API level, and they map to different actions in the bundle. In the bundle YML you'd need to maybe pass in a blank string, (or have a default val for the var in TF) and check for that in TF. 

2) If we're looking to persist the secret in some form, rather than encrypting it why not just store the secret in KV and persist the URI (or secret name + KV ID) to the object in Cosmos? If you avoided referencing a specific secret version then the secret could be rotated without any impact. The secret name and KV ID would be passed to TF which could grab the value as needed via a data block.

**Comment by ross-p-smith** [comment]
The question is how do we store the value in KeyVault in the first place. The value we want to store is created outside of TRE, by an AAD Administrator. It has to be passed into TRE
1) We could ask the AAD Administrator to add it to the KeyVault, but now we have an AAD Admin doing an Azure Role.
2) We could have an API that has one responsibility: adds secrets to a workspace vault and it doesn't do it through TF. This would have to be done after the Workspace is created.

**Comment by damoodamoo** [comment]
I'm not sure how a secrets API endpoint would work given all the mechanics of the API trigger a deploy after the resource is initially posted?

**Comment by damoodamoo** [comment]
yea it may well be better to not persist them anywhere - but it's only the workspace creation secret that is problematic isn't it? Once the workspace is there all subsequent secrets could live in the workspace KV?

**Comment by tamirkamara** [comment]
1. I'm supportive of going one step forward without persisting the secret anywhere for now. But, are we sure we don't have any "update" or custom actions that are going to suffer from this? @marrobi, do you know?
2. +1 on the idea to persist into keyvault (instead of encrypt/decrypt) longer term.

**Comment by tanya-borisova** [comment]
@damoodamoo 

> but it's only the workspace creation secret that is problematic isn't it? Once the workspace is there all subsequent secrets could live in the workspace KV?

They will live in the workspace KV, the problem is how they get there. In a scenario when a secret is supplied by the user, which is what we're discussing here, the secret is supplied in the request, and currently all of the parameters from request are stored in Cosmos (including the secret, unencrypted), and that's going to be true for any resource.

I don't think we can make requests to store secrets in the workspace KV from the API, as workspaces are not accessible from core by design (https://microsoft.github.io/AzureTRE/azure-tre-overview/networking/#workspaces)

**Comment by damoodamoo** [comment]
I didn't appreciate the network isolation aspect between Core / Workspaces. An idea to discuss then:
- New KV in core dedicated to storing resource secrets. 
- We find a way to identify a property as being a secret (we need to do this for any approach I guess)
- In the API, we scan the properties, find any secrets, push to KV and store the secret name in Cosmos instead

... this is only if we feel there's a need to store the secrets at all, which I guess is also up for debate :)

**Comment by tanya-borisova** [comment]
@damoodamoo That sounds good and in line with what @ross-p-smith  and I discussed offline yesterday. 
I think for the first step I'll make the change to stop writing secrets to Cosmos, for which, as you say, we also need to identify which properties are secrets. Then as a second step we can make the KV change.
