### ISSUE TITLE
Airlock - data cleanup (deletion) when moving between stages

### ISSUE THREAD

**Issue by eladiw** [microsoft/AzureTRE#1963]
## Description

As a TRE Developer
I want data to be deleted from the source location after it has been copied to the destination location
So that data which is no longer needed will not accumulate over time (cost, cleanup)

## Acceptance criteria

- [ ] Deletion is triggered when the copy is done via a dedicated event
- [ ] Deletion does not block any other operation
- [ ] Airlock processor should handle the deletion

**Comment by tanya-borisova** [comment]
I spoke to @tamirkamara about some considerations when implementing this. There are two ways to go about it:

1. Slightly quicker way: blobs are deleted in BlobCreatedTrigger, once we receive notifications that the new blob is created (in destination storage account). There already is a comment on line 57 saying that this is where we can delete the old container. This would fit the existing design nicely, but would further couple the copying and deleting of blobs to the Airlock processing logic.
2. Slightly longer way: instead of immediately deleting blobs in BlobCreatedTrigger, we issue a new event. In the listener of this event, we delete the blob. This would then make things more consistent in preparation to  https://github.com/microsoft/AzureTRE/issues/2277 , where copying of blobs will also be done via a copying event.  This option would mean that we need to create a new topic. There were some instabilities uncovered when using system topics with Event Grid, but since it's not a system topic, it shouldn't cause any trouble.

I'm inclined towards option 2. 
cc @eladiw
