### ISSUE TITLE
Airlock - fix export in progress to export approved networking

### ISSUE THREAD

**Issue by eladiw** [microsoft/AzureTRE#2098]
**Describe the bug**
When the AL processor tries to copy data from the Export inprogress to the Export approved storage it fails on 403 unauthorized.
To overcome this, the fw of the export in progress storage is allowing communication from the airlock processor subnet. 

If possible, remove this fw allow rule and replace with a PE connection in the export approved storage (so they talk over private link).
This user story is about trying to make the communication flow using private link rather public fw.

**Comment by yuvalyaron** [comment]
Seems like we can't copy blobs if the source storage account is accessible to the calling client only via a private endpoint
that exists in a peered VNet.
opened a support case and waiting for their response.  support request ID: 2208210010000181

**Comment by yuvalyaron** [comment]
An incident for the PG was opened for the case.

Regardless, the support team has mentioned that they verified, and for setups like ours, where we enable the peered VNet traffic in the firewall settings of the storage account, the copy is done through the private link, and not through the public internet. It can be verified by us if we enable storage diagnostics and check that the calling IP of the "GetBlob" operation is a private IP.

**Comment by yuvalyaron** [comment]
The incident was closed, the PG said that copying in such setup is not supported, and will not be supported. They will fix the documentation to reflect that.

The PG explanation:
`In this setup, the traffic starts from destination VNet and goes to destination account, which means the source VNet is unused (the traffic won't go through the source VNet if it doesn't need to). So when the destination account gets the request, the request is from the destination VNet only. And when the destination account talks to the source account, the source account only sees the destination VNet. That's why the source account rejects the request.`

However, I checked the storage diagnostics, as the  support team has suggested, and it seems like the "GetBlob" 
operation is called from a private IP, so copying is done through the private link anyway.
