### ISSUE TITLE
Airlock - Enumerating all files when submitting a new request

### ISSUE THREAD

**Issue by eladiw** [microsoft/AzureTRE#2267]
## Description

As a TRE Developer
I want to enumerate all (currently single) files and save the list inside the request object
So that it can be used by the UI and other validations

## Acceptance criteria

- [ ] The request object inside Cosmos contains the files list (currently it is empty)

**Comment by tanya-borisova** [comment]
File size could also be included

**Comment by tamirkamara** [comment]
We realized this isn't an easy thing to accomplish - the first place where this could have been implemented is in the API, but due to network restriction it can only enumerate files for an import request but not for exports.
The only way this could be done is to have the airlock_processor do this work and return the information via a message for the API to update in cosmos. This means that the information would only be available **after submit**.

**Comment by jjgriff93** [comment]
Hmm, so after submit would be fine in terms of showing the file info to a reviewer; I guess the main drawback would be for the initiator. If they upload files using storage explorer they won't see those files in the UI. Not the end of the world
