### ISSUE TITLE
Airlock - add file size limit sanity check

### ISSUE THREAD

**Issue by eladiw** [microsoft/AzureTRE#2270]
## Description

As a TRE Developer
I want to define the airlock Maximum file size and fail the request if given file is larger
So that we won't try to process too large files

## Acceptance criteria

- [ ] Validate the airlock max file size
- [ ] validate our dependencies limit
- [ ] min(a, b) is our limit
- [ ] if file size > limit -> move to failed state (issue 2268)

**Comment by yuvalyaron** [comment]
This cannot be checked from the API, import requests can be supported but we need to add a private endpoint to the storage account for them to work.
Export requests are not supported at all, as the API cannot  reach the export storage account (which is in the workspace).

I have this branch where I tried to implement it in the API - but couldn't because of the issues I mentioned:
https://github.com/microsoft/AzureTRE/compare/main...yuvalyaron:AzureTRE:yuvalyaron-feature/2270-airlock-add-file-size-limit-check?diff=split

We can implement it in the resource processor as the described in the original issue,
but it should be done after https://github.com/microsoft/AzureTRE/issues/2268

NOTE:
this is also applies to https://github.com/microsoft/AzureTRE/issues/2339

**Comment by yuvalyaron** [comment]
Since the malware scanning (our dependencies) team will handle file limit on their side, it's better not to add a hard limit on our side, as their limit might change. Also since this cannot be checked from the API, requests will only fail after submitting them, resulting in a bad user experience.
