### ISSUE TITLE
UI not able to retrieve Workspace scope and token for non-admin users

### ISSUE THREAD

**Issue by tanya-borisova** [microsoft/AzureTRE#2404]
**Describe the bug**

When logged in as a user that has TREUser and WorkspaceResearcher roles, I can't retrieve the Workspace, even though as a WorkspaceResearcher I should be able to. 

![image](https://user-images.githubusercontent.com/52954123/182592143-284a36b5-27a7-43e7-8fb1-ab269460cd9e.png)

If I then grab a token which was sent to the API, I only see TREUser as a role in it, and not the WorkspaceResearcher, which suggests a wrong token was sent.

![image](https://user-images.githubusercontent.com/52954123/182592062-54ae13a1-0e06-4175-8973-592ad70c1310.png)

**Comment by jjgriff93** [comment]
A number of these 403s like the workspace/operations call should fail as the WorkspaceResearcher role doesn't have permission within the API to access them, so the UI should not make these calls if the user is a researcher and instead only show the basic details of the workspace. Still investigating if some of the other calls should work and what's going on with the token

In the meantime will open reducing the workspace fetches as a new task
- [ ] UI: Researcher should only see workspace description, history and calls to /operations should be removed

**Comment by jjgriff93** [comment]
After investigating further it looks like the UI is trying to get the workspace via `workspaces/{workspace_id}` to then get the scope_id to get another token for the workspace (where the user will then have the `Workspace_Researcher` role to access the workspace content). However, this isn't possible because the researcher doesn't have permissions within the TRE scope to get the workspaces: 

![Image](https://user-images.githubusercontent.com/25235950/183962546-6aaef09c-9e07-4481-a33a-ecc7fc8bd8ed.png)

So I think the best solution here is to add a permission in the API for researchers to fetch individual workspaces by ID as they already have permissions to list all of them (hence why the workspaces screen works but the individual workspace view does not)

**Comment by marrobi** [comment]
@jjgriff93  As long as they can only list/get their workspaces, that is fine.
