### ISSUE TITLE
Shared Services are shown in workspace view for TREUser

### ISSUE THREAD

**Issue by lenisha** [microsoft/AzureTRE#2545]
TREUser should not have access to shared services like Firewall etc . They do not show in home screen, but are shown in left tree when user selects workspace 

**Steps to reproduce**

1. Login as TRE User and TREResearcher in one of workspaces
2. Home page shows only allowed workspaces
3. Navigate to Workspace, and Left tree shows shared services

**Comment by marrobi** [comment]
@lenisha as per the PR discussion, this is by design, we need shared services to be visible in the workspace view so that users can interact with them from the workspace UI. 

If feel there is a compelling reason for this to be different, let us know. 

It might be we could hide some shared services based on "category" which I know is something you have considered.
