### ISSUE TITLE
Firewall rules priority

### ISSUE THREAD

**Issue by chboudry** [microsoft/AzureTRE#2920]
Customer would like to add some rules within the TRE firewall that relates to its workflow, such as allowing connection to a SQL database.

Common practice is to define custom rules above system (TRE ones)  but we can't do that in TRE as the system ones starts as 100 priority and that is the minimal priority level one is able to use in the firewall.

![image](https://user-images.githubusercontent.com/51988290/204330867-a7418674-5faa-40f8-a04c-4e16b684c0a7.png)

Request would be to start TRE rules on a higher number.

**Comment by marrobi** [comment]
@chboudry can you give an example of a rule that would need to be higher priority? 

Why not add them at 5000? 

Ideally this needs to be in the TRE state store too, otherwise the rules may get lost.

**Comment by tamirkamara** [comment]
We have seen examples of customers using custom workspaces and adding the rules there. Isn't that an option?

**Comment by chboudry** [comment]
@marrobi it is a security best practice to enforce a default deny strategy for firewall rules.
Default deny should be explicited (highest number == low priority), system rules come next (lower number == higher priority), and then customer rules.

TRE does not set up a deny rules, so yes, customer *could* create rules with a higher priority number and that would work, but it would be nice to stick to default security recommendations and having homogeneity across solutions as it is already done this way on NSGs.


"Ideally this needs to be in the TRE state store too, otherwise the rules may get lost." -> that's true, they will have to creat a new firewall template, but it will be more convenient then if they don't need to update all the rules :) 

@tamirkamara not sure what you mean, intent is to edit firewall on Core so that customer can access database from any workspace vm.

**Comment by tamirkamara** [comment]
This is what I had in mind: https://github.com/microsoft/AzureTRE/blob/main/templates/workspace_services/guacamole/template_schema.json#L69
Each workspace could potentially add their own rule to open what is needed.

If this is a system wide decision I think any number below 200 is valid as that is where we started the internally managed ones (maybe we should start higher...).
Anyway, the first few in the 100 range are core ones we setup for the system. Since this seem to be relevant for workspaces only I think 195 is a good number to pick for that one rule to all db access to all workspace.

**Comment by tamirkamara** [comment]
With the move to firewall policy I belive this issue is now kind of obsolete. Do you agree @chboudry?

**Comment by chboudry** [comment]
okay
