### ISSUE TITLE
Destination for Azure Blob Storage has specific URL requirements that are not obvious

### ISSUE THREAD

**Issue by ahmed-alhindawi** [microsoft/AzureTRE#3225]
**Describe the bug**
Upon attempting to download from blob storage following an approved AirLock process, an `Azure CLI` command is generated with the SAS token - all that is required is to change the destination folder path. However, the destination path must not be within quotation marks

**Steps to reproduce**
1. Upload to an airlock using the usual method
2. A URL will be generated which looks like: `az storage blob download-batch --destination <~/destination/path/for/file> --source SOURCE-HASH --account-name ACCOUNT-BAME --sas-token "REALLY-LONG-SAS-TOKEN"
3. Notice the `<~/destination/path/for/file>`; this should be a fully formed path and not in quotation marks (e.g. it cannot be "~/". Otherwise, an error stating that "incorrect usage: destination must be an existing directory"

Would be good to specify that in the documentation or ensure that the error is appropriate for the error.

**Comment by yuvalyaron** [comment]
The problem is not about using quotation marks, but rather the combination of quotation marks with this specific destination: `~/`.

For instance, this command works:
` az storage blob download-batch --destination "/home/yuval/"  ...`

This is more of an Azure CLI issue than a TRE issue. To clarify the usage, I removed the `~` from the path in the command, which should direct toward using the full path instead.
