### ISSUE TITLE
Airlock - workspace data export (Design)

### ISSUE THREAD

**Issue by christoferlof** [microsoft/AzureTRE#33]
Preventing data exfiltration is of absolute importance but there is a need to be able to export certain products of the work that have been done within the workspace such as ML models, new data sets to be pushed back to the data platform, reports, and similar artifacts. 

A high level egress workflow would look like:
1.	Researcher uploads (or links to?) data via the TRE web portal from within a workspace
2.	Data is scanned for viruses (and potentially PII)
3.	Data export approver receives notification. They log onto a secure VM and can view file, and results of scans.
4.	Once approved data gets moved to a staging location
5.	Data can be downloaded by the researcher from via the portal from outside the workspace

**Comment by mjbonifa** [comment]
The dataflow described is a pipeline/data supply chain with governance (i.e. contracts, licensing, etc) controlling ingress and egress.

Staging inputs and outputs can be considered an activity in a pipeline with different roles, responsibilities and tools to those used to produce the artefacts themselves.

Now, the primary resource within a TRE that provides governance boundaries is the "workspace".

One idea would be to consider ways to connect/orchestrate workspaces each with distinct ingress/egress policies governed and aligned with contracts/SLAs/agreements etc as appropriate. For example, 

Ingress Staging Workspace (linking, pseudonymisation, de-identification, etc) -> ML Workspace (artefact production) -> Egress Staging Workspace (as above)  

By using the workspace construct to flexibly provision environment and data controls (in the context of the principles of the 5 safes) we can create assurances that the workspace meets the legal requirements, etc.

A pipeline of workspaces would also start work towards federation of TREs.

**Comment by marrobi** [comment]
Interesting way of thinking about it.

So everything is a data import "job" specify to a destination workspace.

Can all users request to send data to any workspace (maybe even in another TRE), or only to workspaces they are a member of?

There still needs to be an approval flow, do we have  `Data Reviewer` role (say Workspace Owner for now), who can see all artefacts that are pending approval to get into their workspace, and simply move it from a transfer location into their workspace shared storage should it be "approved"?

How does the approver then get it to the Researcher's outside location - say client machine? Is this a special case. Do they need to be able to download their approved exports?

**Comment by marrobi** [comment]
@joalmeid @daltskin we need to decide if we are treating "airlock import/export" as a single feature or two for initial iteration. I'm happy either way, I had them as one, but then split it as we were going to focus on export first, and was a requirement for some workspaces to have one but not the other.

There is a lot of common ground, however might be worth considering requirements first. 

I think @mjbonifa's diagram above is useful. As a start I'm thinking each workspace has an inbox and outbox, only accessible by the Data Steward/Airlock Manager for that workspace? 

@mjbonifa understand in some scenarios data will not move, and this is about granting access, but feel the first iteration, based on previous work and customer requirements should focus on the movement of artefacts. I also think we should focus on external locations as source and destination, although remembering that another workspace inbox as a external location should be considered down the line.

The next stage is to define how data is transferred from:
- **source location** -> workspace **inbox** -> approval -> **workspace storage**
- **workspace storage** -> **outbox** -> approval -> **destination location**

Previously we have done this with file shares and storage explorer- might be acceptable for staging and download, but we need a more streamlined method with approvals.

**Comment by mjbonifa** [comment]
@marrobi it makes sense for each workspace to have an inbox and outbox as you describe them, that construct allows us to work towards the above scenarios

Yes to **remembering that another workspace inbox as a external location should be considered down the line** maybe we should break this out into another issue?

Another point is that the diagram above could be interpreted incorrectly. The workspaces for risk management could be anywhere within a dataflow depending on the scenario. These are not just at the boundary between the TRE and processes external to the TRE, as could be assumed.  

Understand that a first version will copy data through the process for now

**Comment by marrobi** [comment]
Two new features
- [ ] As a TRE User I want to export data to another workspace in the TRE
- [ ] As a TRE User I want to export data to a workspace in another Azure TRE instance

Re dataflow think we need clearer use cases, feels to me this is more of a data pipeline with with defined activities, including approval, between each movement of data/change of data access) . The workspace inbox/outbox being stages in that pipeline.

**Comment by joalmeid** [comment]
There has been some previous experiences/attempts on this. Coming from fresh perspectives, and focusing on a first iteration for airlock processes, believe in a few facts to start with:

- Airlock export/import to be separate features, but requirement wise, there must be alignment.
- Workspace must contain inbox (storage share)
- Workspace must contain outbox (storage share)
- Outbox (storage share) should be reachable from a TRE system principal to enable sharing across workspaces
- TRE Composing service implementing airlock sub-processes including virus scan, 
- TRE API allowing to start/list/stop import/export processes, per workspace
- TRE must notify the individual/group with Data Steward role of a pending approval
- individual/group with Data Steward role must the only with access to the data in the airlock process
- TRE API allowing to approve/deny airlock process, moving data accordingly

> This focus mostly on data copying and not providing data access

**Comment by CalMac-tns** [comment]
I posted this in 1109 but makes more sense here, I have reviewed the stories for data ingress / egress and moving large data files around and I thinking that there may be a simpler solution to this problem, does require some manual input but there are a lot of advantages.

**1. Researcher uploads data via specific workspace in the TRE web portal**
**No**, only the PI should be able to copy agreed data into (or out of the Workspace) - only the PI has authority so they should be the ones with the security access to do that.  This creates a real-world airgap in the form of the PI.
The inbox / outbox requirement just becomes a storage/security issue INSIDE the VM.  The PI can add/delete files in the inbox but can only read from outbox, the reverse is true for the researcher.
**2. Data is scanned for viruses (and potentially PII)**
I believe this can only be outside of the TRE, therefore done through standard virus checking processes.  Data must arrive on a UHS server before it arrives at the TRE - that would be the logical place to scan for virus.
**3. Data import approver receives notification. They log onto a secure VM and can view file, and results of scans.**
In the example below the approver is the PI and is the one controlling the data movement, it is the researcher that is notified when the PI copies the data into the workspace.
**4. Once approved data gets moved to user storage in the workspace, and researcher notified**
This step not required because it is the PI who controls the data movement process not the researcher and is accommodated in step 3.

This process solves the following:
1. Researchers cannot copy data in or out of the TRE.
2. The PI is responsible for all data movements.
3. Data is only copied into the TRE once approved - it's the PI's responsibility.
4. All files that are copied into, created in, or deleted from the VM storage is automatically logged.
5. Any size and any number of files can be dealt with using Storage Explorer.

The "airgap" is created by default and is a function of the security credentials of the PI. Unless the PI actively does something data does not move.

![image](https://user-images.githubusercontent.com/74237053/155333535-01874220-e34f-4738-bed2-386cf54747a3.png)

**Comment by mjbonifa** [comment]
@CalMac-tns 

* Generally agree with the approach as it's essentially how it works today in terms of responsibilities. 
* Agreed that it's the PIs responsibility for projects conducted in workspaces. I'd prefer to be precise on roles as PI is not something in the Azure TRE terminology. Azure have "TRE workspace owner" which maps onto PI in some settings
* We may want to consider a Data Steward Role that a TRE Workspace Owner can delegate to, to manage the ingest on their behalf. There are many situations where the PI has responsibility but not necessarily the technical skills to manage data and therefore delegates to a senior member of the research team to take the action.
* We must explicitly consider the boundary of a TRE and the boundary of a workspace, along with the distribution of function between them. i.e. what is shared and what is workspace specific. In your diagram it's not clear to be if Audit and Notification are Workspace Resources or Shared Services. 
In the figure below I've put a box around the workspace resources and also questions regarding functions associated with audit and notification.

If in the shared space then appropriate governance rules will need to be created for them for the connections between workspace and shared services

If in the workspace the appropriate processes established to get the audit data and any other info out of a workspace. I'd suggest that the audit function is a separate issue and relates to many events related to the workspace. Hopefully there's a place to discuss that elsewhere.

![data-import](https://user-images.githubusercontent.com/64203637/155679934-5a7fa245-dba2-47a4-8722-715a9cdea282.png)

**Comment by CalMac-tns** [comment]
Yes I agree, to bring the requirement for delegation into scope we would need to introduce the staging area back into the process, we can't delegate access to a file etc if the rest of the TRE doesn't have visibility.

The process would be as follows:

1. PI or Owner receives the data outside of the TRE but within the scope of UHS Network. (as they do now)
2. The PI or Owner then copies the data to the staging area - only THEY can see this data at this point.
3. They can continue as PI or delegate, my idea as that delegation is to simply run a script such as **"delegate files[*] workspaceid email"** which changes access in the files in the staging area and creates the appropriate permissions within the workspaces.
4. The delegate can then continue as PI delegate

The same process can the be reversed to get data out of the TRE because the permissions are only shared between the PI/Delegate and researcher.

The audit log is outside of the workspace but inside the TRE so that access can be gained for audit purposes, it should only contain metadata so no IG issues. The email would be a shared service but I'm open to suggestions on how notifications are handled.

Also agree that we need to decide what gets audited separately.

![image](https://user-images.githubusercontent.com/74237053/155733346-d5c8f861-c13e-4a33-8924-81a43f198739.png)

**Comment by marrobi** [comment]
@CalMac-tns thanks for the input, a good discussion. I am conscious that we need to focus on requirements - from multiple sets of requirements- rather than specific implementation details at this point. There also is a bit of confusion around import vs export - we need to consider both flows.

@joalmeid is going to create some user stories from the various sets of requirements then we will work to create a technical architecture that meets this.

**Comment by joalmeid** [comment]
I've went through a set of existing requirements, guidance from HDRUK and current inputs on GH airlock import/export.
Without taking any look into implementation details, there's a suggestion for the user stories of airlock export:

Considerations: 
- Bullets would be acceptance criteria
- Workspace Data Steward can be TRE workspace owner, in initial phases 

As a Workspace TRE User/Researcher
I want to be able to upload data file (zip) to the export draft area
So that the data is available to start the airlock export process 
	- Researcher has access to the export draft area
	- Researcher can invoke the export process 
	- Export process gets logged for auditing purpose
	
As an automated process in TRE
I want to execute the gates defined in the TRE export process
So that I guarantee safety of the data
	- Defined set of workspace export gates that can be selected for export validation (ex: PII scanning)
	- Notify the Data Steward and/or requester once all the gates are complete with an export process id
	- Data Steward can access the export draft area
	- Artefacts ingested into the export draft area must be read-only
	- Export gates results are logged for auditing purpose
	
As a TRE Data Steward
I want to be able see an airlock export process status by process id for a workspace
So that I check the current overall export status and results of all the export gates in the airlock process.
	- A TRE API method to retrieve the current status of an existing airlock process
	
As a TRE Data Steward
I want to be able to update the airlock export approval state
So that the airlock export process terminates and artefacts in the original request get deleted.
	- A TRE API method to update the airlock process with a true/false and an optional comment
	- [Approved] - Automatically copy the artefacts from the export draft area to the export approved area
	- Automatically delete the artefacts from the export draft area
	- A notification is sent to the Data Steward and/or requester with the airlock process final status
	- Approval status (approved/denied) of the Data Steward logged for auditing purpose

As a TRE User/Researcher
I want to be able to access the artefacts in the export approved area
So that I can copy or use them within my workspace
	- The export approved area is only available to the requesting TRE User/Researcher
	- The Data Steward must be able to access to the export approved area 
	- The requesting TRE User/Researcher and Data Steward cannot delete the artefacts in export approved area 
	- Log any access to artefacts in export approved area for auditing purpose
	
[NOT MVP]
As a TRE User/Researcher
I want to be able to identify export container (destination)
So that the airlock export process, has it identified as single destination

As an automated process in TRE
I want to execute a PII scanning gate on the artefacts in the export draft area
So that no PII information leaves the workspace
	- Generate a PII scanning report
	- Save the result/output of the gate
	- Each run of the PII scanning gate gets logged for auditing purpose

**Comment by CalMac-tns** [comment]
Thanks for the input @joalmeid , taking the story a step further how would PII scanning actually work with the TRE? 

How would we deal with situation where a PI (Principal Investigator) delegates authority to someone else?  In the story above a delegate would be similar to a Data Steward but would only get the role once delegated from the PI?

**Comment by daltskin** [comment]
Does the Data Steward assignment need to be considered for the scope of this story?
These stories assume the Data Steward role has already been assigned to individual(s) for that workspace
The PII scanning could be an automated process (TBC) using a system account.

**Comment by marrobi** [comment]
A user would be able to be assigned the Workspace Data Steward role at any point in time. Does that fit that need?

**Comment by SvenAelterman** [comment]
@marrobi Finally adding to the discussion here... I have started building Bicep templates to implement the flow found in the Architecture Center reference (https://docs.microsoft.com/en-us/azure/architecture/example-scenario/ai/secure-compute-for-research). This reference was written by one of my peers and it's commonly implemented in US EDU.

At this time, my templates are missing the Logic App to perform the approval. I am also reconsidering hosting the Azure Data Factory in the hub. It might just make sense to deploy the whole thing as a workspace service, instead of partially as a shared service, partially as a workspace service.

See the GitHub repo here: https://github.com/SvenAelterman/AzureTRE-ADF

I've also read something about virus scanning. Azure Storage has that built-in, but last time I checked, there's no event when the scan is finished and it can take hours. So I had previously developed an integration with VirusTotal, which can be found here: https://blog.aelterman.com/2021/02/21/on-demand-malware-scanning-for-azure-storage-blobs-with-virustotal/

**Comment by joalmeid** [comment]
Thanks @SvenAelterman . We're trying to crystalize the requirements and flow that makes sense in a TRE. Haven't break it down into implementation, but sure it will help. The airlock processes are definitely bound to a workspace. 
Regarding the malware scanning, we're also exploring other future Storage features we may use. Otherwise there is a similar implementation focused on az functions, storage and Windows Defender in a VM. It hends up being quite similar to the VIrusTotal

**Comment by marrobi** [comment]
@SvenAelterman a thought - what if had a data factory self hosted integration runtime in the core/hub resource processor subnet, as this has access to all the workspace VNets (as the resource processor has to carry out data plane operations) so would be no need to add managed private endpoints.

Also any outbound traffic can also be routed via the Azure firewall to prevent data exfiltration and for auditing purposes.

What do you think vs managed network?

**Comment by SvenAelterman** [comment]
@marrobi Hadn't thought about that yet. It could be a useful solution. At the same time, it's yet one more VM to manage. I am not sure how most customers would balance that.

**Comment by marrobi** [comment]
@SvenAelterman it could be run on a container instance maybe as per https://docs.microsoft.com/en-us/azure/data-factory/how-to-run-self-hosted-integration-runtime-in-windows-container, but that doesn't support auto update.

If a VM could likely be B series, with auto updates of the OS and integration runtime.

**Comment by eladiw** [comment]
design is done
