### ISSUE TITLE
Cannot access storage explorer from Guacamole Virtual Machine

### ISSUE THREAD

**Issue by slawpast** [microsoft/AzureTRE#3322]
Added application rules for the following domains:
`
*login.microsoftonline.com,*microsoft.com,*adfs.########.com
`
We try to login to azure cli using command **az login --use-device-code** and get following error.

![image](https://user-images.githubusercontent.com/107872721/223416692-35b892df-ecc0-435b-be96-a7e920e03b31.png)

**Comment by marrobi** [comment]
Are you opening the device code page inside or outside of the TRE? Typically it would be opened outside.

Also I recommend you use service tags, AzureActiveDirectory rather than FQDNs.

**Comment by slawpast** [comment]
hi @marrobi 

The device code is being opened inside TRE.

I have added network rule as a service tag for AzureActiveDirectory as well:


![image](https://user-images.githubusercontent.com/107872721/223440923-d622dcac-38ad-4d88-a80d-7be2e679479b.png)


Still have the same issue.


I have also attached below an error when connecting from Azure Storage Explorer in Azure TRE

![image](https://user-images.githubusercontent.com/107872721/223441545-83e0af6a-78ce-4dd4-ade8-ab61c82b3908.png)

**Comment by marrobi** [comment]
Is there a reason  that you cannot open the device code page from outside the TRE?

I expect traffic is being blocked by the firewall, if you check your browser tools, you should be able to identity what.

**Comment by slawpast** [comment]
@marrobi Outside the TRE we are able to login, and that's not the issue.
Inside TRE, when we try to use Azure Storage Explorer, we have Sing-in error, as shown on the screenshot above.

**Comment by marrobi** [comment]
@slawpast that's not the title or the issue description... "Ad account login from a Virtual Machine fail due to CA certification issue." There is no mention of storage explorer. It's very hard to help you when the issue is not clear... 

For the storage explorer error have you checked the firewall logs to identify what traffic might be being blocked? 

The storage explorer docs, provide guidance here - https://learn.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=Windows#authentication-logs and here https://learn.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=Windows#network-logs for more in depth troubleshooting.

We typically only use storage explorer for airlock operations, and in that case have SAS tokens. 

I will try reproduce the error in the next couple of days.

**Comment by slawpast** [comment]
@marrobi 
apologies for the misleading title description. I tried to use "Sign in with Azure" from Storage Explorer using the settings mentioned in #3302. However, that did not work and got the error mentioned in the message earlier. Therefore, I tried to use sign in using device-login to see if that works and even that failed with CA certificate error. This made me think that these issues might be related, hence the title of the ticket.  Happy to close this ticket and recreate one with an appropriate title if that helps.  Thank you for providing these links, I will try to investigate and get back to you. Would also be great to know if you are able resolve this when you get a chance. Thanks

**Comment by marrobi** [comment]
When you use sign in to Azure, Storage explorer connects to `management.azure.com` to get a list of storage accounts.

You will need to allow this on the firewall. This may or may not be seen as a security issue dependant on your specific IG requirements.

I've tested this works, so will close the issue. Let me know if need any further help.

**Comment by slawpast** [comment]
Thank you for your help in this matter @marrobi.
Adding `management.azure.com`  to firewall policy rules solved the issue.
