### ISSUE TITLE
user permissions error

### ISSUE THREAD

**Issue by pselmani** [microsoft/AzureTRE#3323]
Hi,

I have created ad domain services TF module and integrated with Core. It picks it up and terraform validate works when I run make deploy-core but fails at last hurdle with below error.  Which user is it referring to as I can't find it on AD

I have done AZ login before hand and I can create ad domain services over the Portal so it seems to be using some different account

![image](https://user-images.githubusercontent.com/68639496/223421665-a8ebce7e-3a09-45d8-941f-2143f1e020f3.png)

Thanks

**Comment by pselmani** [comment]
I have checked all the User IDs and Enterprise Application IDs but can't find that user it's referring to

**Comment by marrobi** [comment]
Firstly I would avoid modifying core, and try to use shared services or create a feature request to and make discuss making changes upstream. The reason being your changes can block upgrades to future releases we make. 

Where are you executing the command from? Unless you have `ARM_CLIENT_ID` set terraform should use your Azure CLI login. Are you searching for the object ID in the correct tenant?

**Comment by pselmani** [comment]
Thank you for your response

That does make sense about core, that did cross my mind. Our challenge is that TRE will be deployed to a new Subscription but will need to make use of an existing AD Domain Services (due to AVD). So not sure at what extent it needs to be integrated into the TRE framework or can it stay completely out of its scope

In regards to error, 'ARM_CLIENT_ID' pointed me to the correct Service Principal, thanks again

**Comment by marrobi** [comment]
In this scenario I'd keep ADDS completely separate, typically part of the customer landing zone. the TRE networks can peer to to the network that ADDS sits in. The peer can be added  in separate TF state. 

We do similar in our workspaces: https://github.com/microsoft/AzureTRE/blob/b63e7eeda3b8690c4fff9961b067dec615adb6cd/templates/workspaces/base/terraform/network/network.tf#L45-L67

Ass for AVD. I don't believe ADDS is a prerequisite any more,  it will work with Azure AD.

He had this set up as a PoC - see pull request here - https://github.com/microsoft/AzureTRE/pull/1865

This is in Bicep, we would likely use terraform going forward to be consistent.

We don't have any production AVD customers ass far as I am aware due to the issue identified here - https://github.com/microsoft/AzureTRE/pull/1865#issuecomment-1269528496 . Also AVD does not support AD guests (researchers are usually guests), or Linux VMs.

If you want to try do a PR to integrate AVD, happy to help as something that often comes up.
