### ISSUE TITLE
Deployment custom Windows Virtual Machine workspace service failed.

### ISSUE THREAD

**Issue by slawpast** [microsoft/AzureTRE#3345]
As an AzureTRE admin I want to deploy a customized windows virtual machine from an image stored in Azure Compute Gallery.
When deployed in AzureTRE  workspace service UI we got the following error:
` Error message: Unable to find image 'arctremric01.azurecr.io/tre-service-guacamole-windowsvm-custom@sha256:fe806a279359d88aabb18960b579d827d6ad3c817d5618325f29c290ae8a6ca7' locally [31m╷[0m[0m [31m│[0m [0m[1m[31mError: [0m[0m[1mwaiting for creation of Windows Virtual Machine: (Name "windowsvmf713" / Resource Group "rg-tremric01-ws-d6da"): Code="OSProvisioningClientError" Message="OS Provisioning for VM 'windowsvmf713' did not finish in the allotted time. However, the VM guest agent was detected running. This suggests the guest OS has not been properly prepared to be used as a VM image (with CreateOption=FromImage). To resolve this issue, either use the VHD as is with CreateOption=Attach or prepare it properly for use as an image:\r\n * Instructions for Windows: https://azure.microsoft.com/documentation/articles/virtual-machines-windows-upload-image/ \r\n * Instructions for Linux: https://azure.microsoft.com/documentation/articles/virtual-machines-linux-capture-image/`

**Steps to reproduce**

1. Create a VM:

![image](https://user-images.githubusercontent.com/107872721/225304308-c35b13c3-ac2a-4d0e-abde-3bdf8f157195.png)
![image](https://user-images.githubusercontent.com/107872721/225304332-8c6523fd-bf86-4840-9c52-dd4c7fea5ad5.png)
![image](https://user-images.githubusercontent.com/107872721/225304377-9d7a0be5-fd19-4fe1-86b9-f005508e20a3.png)
![image](https://user-images.githubusercontent.com/107872721/225304431-a2cda2e5-87d0-4967-842f-e8fca88a5e5e.png)
![image](https://user-images.githubusercontent.com/107872721/225304450-fcdfbb14-7209-483d-aaa3-3ce352a302bf.png)

2. Capture the VM:

![image](https://user-images.githubusercontent.com/107872721/225304767-b5f896fa-6e02-4c07-9aba-bfbb38729aa2.png)
![image](https://user-images.githubusercontent.com/107872721/225304806-75583755-1e34-47b3-bd27-464bce1593a2.png)
![image](https://user-images.githubusercontent.com/107872721/225304825-7ea28c76-cefa-403d-bde3-ca6015e05b09.png)

3. Visual Studio Code setup:

- copied the whole guacamole-azure-windows folder from AzureTRE into our repo:

![image](https://user-images.githubusercontent.com/107872721/225306430-cb99e14c-c23d-4109-9138-476693a74dd3.png)

- modified template_schema.json to include new os_image:

![image](https://user-images.githubusercontent.com/107872721/225307759-3cc2d8fa-c4ab-4a6e-8c62-b33952edc4ed.png)

- modified porter.yaml file to include new image option:

![image](https://user-images.githubusercontent.com/107872721/225307854-445d0557-0a19-48d0-846c-9bf395f7d7f6.png)

- added default image_id in porter.yaml file

![image](https://user-images.githubusercontent.com/107872721/225307971-7daebd5c-3e3b-4bd5-8dba-1180085a2889.png)

 - Modified makefile for command

![image](https://user-images.githubusercontent.com/107872721/225308489-7681fb94-bb0c-4e07-b77c-fe67b86b0526.png)

- Run command

make user_resource_bundle_custom WORKSPACE_SERVICE=guacamole BUNDLE=guacamole-azure-windowsvm-custom

**Comment by marrobi** [comment]
@damoodamoo @martinpeck are you able to assist with this?

Thanks.

**Comment by marrobi** [comment]
@slawpast as a first step, can you successfully create a VM from the image in the Portal? 

So not touching the TRE project.

**Comment by martinpeck** [comment]
Hi there @slawpast. There are a couple of things to work through here.

First, I've not had much luck with the "capture a VM image" approach in the past. That's not to say it won't work, but I've tended to start from a base image and then use Azure Image Builder to create images. This repo is one I put together that does this: https://github.com/martinpeck/custom-vm-sample-toolkit

Second, as @marrobi says, you should first confirm that you can take your VM image and create VMs from it without the TRE being involved. If that works then that's great. 

Next, assuming you can create VM instances, it's probably worth reviewing that your VM doesn't have any scripts (e.g. cloud init) that run on startup that require internet connectivity. Within the TRE that might be the issue, and your VM might be hanging based upon connection issues.

Finally, I see you've updated your porter.yaml to explicitly point at the Compute Gallery. That works, but there are other ways to do this. I suspect that's not the issue, but I wanted to mention it.

Is everything in uksouth? i.e. your TRE as well as your Custom VM?

**Comment by slawpast** [comment]
Thanks @marrobi and @martinpeck 

I tried to create VM from the image using Azure Portal (without TRE) and have the same issue, so it's not TRE related. 

Regarding "capture as a VM image", it works for a Linux VM when deploying to TRE workspace, so I assumed I can do in similar way for a windows server virtual machine.

Everthing is in UK south, I had to update porter.yaml to specify the default `image_gallery_id,` as for some reason it was not reading it from a config.yaml file.

**Comment by martinpeck** [comment]
Last things first...

Yeah, I think there's a doc bug and a really (nasty) subtle little bug in the config.yaml stuff. @damoodamoo took a look at this recently and may have some bugs/doc changes to make on that side of things.

It's good that the VM isn't working outside the TRE. Well...for some definition of "good" 😀 It's certainly easier to work through without the TRE as part of the repro steps.

As I say, I've hit issues with "capture as VM" before, but I'll give it another go and see if I see the same issue. It looks like you're basically just creating a Windows Server 2019 as a base. Is that right?

**Comment by slawpast** [comment]
Yes, for the purpose of this excersise, Windows Server 2019, however would be great to use other versions, as we do not know yet, what workspace researchers requirements will be.

**Comment by martinpeck** [comment]
**Repro of @slawpast's Experience**

1. Create a Windows Server 2019 Datacentre VM. Other than setting a username/password, I pretty much left everything as the default (including license tick box)
2. Capture VM to Azure Compute Gallery
3. Try and create VM from new Image Template
4. **FAILED** (same issue as above).

**Repro 2: Sign into the VM before capturing the image**

This was an experiment to check if there was any "first run" experience that needed to be triggered before sysprep would work.

1. Create a Windows Server 2019 Datacentre VM
2. Attempt to connect via RDP. Failed due to account username/password
3. Reset the username/password via portal
5. Attempt to connect via RDP. Connected successfully
6. Capture VM to Azure Compute Gallery
7. **FAILED** (same issue as above).

**Repro of @slawpast's Experience, but with Windows 10 Pro**

Performed the exact same steps, but with Windows 10 Pro rather than Windows Server 2019

1. Create a Windows 10 Pro VM. Other than setting a username/password, I pretty much left everything as the default (including license tick box)
2. Capture VM to Azure Compute Gallery
3. Try and create VM from new Image Template
7. **FAILED** (same issue as above).

In all cases, the error is essentially this...

> OS Provisioning for VM '[INSERT_NAME_HERE]' did not finish in the allotted time. However, the VM guest agent was detected running. This suggests the guest OS has not been properly prepared to be used as a VM image (with CreateOption=FromImage). To resolve this issue, either use the VHD as is with CreateOption=Attach or prepare it properly for use as an image: 
> 
> * Instructions for Windows: https://azure.microsoft.com/documentation/articles/virtual-machines-windows-upload-image/
> * Instructions for Linux: https://azure.microsoft.com/documentation/articles/virtual-machines-linux-capture-image/

i.e. no further to understanding why, but the error appears to be consistent across two different Windows base images.

As I say...I've never got this to work, and have generally resorted to doing this from scratch using the git repo I mentioned earlier and building a custom Windows image up from a base OS image using the Azure CLI commands. 

I've no idea why that would work, and this doesn't.

**Comment by slawpast** [comment]
Thank you @martinpeck for your assistance
I have run the following steps:

1. Create a Windows 10 Pro VM. Other than setting a username/password, I also changed Security type to standard (It was also necessary for a linux vm TRE deployment)
2. Login to the VM using rdp (had to add my ip address)
3. Open Power Shell and run the following command:  `& "$Env:SystemRoot\system32\sysprep\sysprep.exe" /generalize /oobe /shutdown`
5. Capture VM to Azure Compute Gallery
6. Create VM from new Image Template 
7. Login using rdp connection.
WORKS, however not done any changes to the original machine and not tested in a TRE yet. I will try to install something at point 2, and see if it exists in TRE.

**Comment by martinpeck** [comment]
My assumption was that this...

![image](https://user-images.githubusercontent.com/1524451/225573787-13daa220-3508-46e0-97c2-67a1fa47813c.png)

... would do the sysprep for you. Once you go through the Capture process the VM is left in a "generalized" state because of this.

I'd expect your approach will work fine in the TRE (and that custom tooling will be present). It's a shame that this isn't working as expected from the portal.

If I find out anything more I'll let you know. I suspect you're unblocked, for now.
