### ISSUE TITLE
[Task]  Configure Gitea registration preferences

### ISSUE THREAD

**Issue by marrobi** [microsoft/AzureTRE#348]
Story: #544 

**Description**
- Need to restrict open registration to Gitea to prevent pushing of code.
- Ideally and admin user created automatically on deploy or AD integration for TRE administrators (only).

Useful - can be set using env vars: https://docs.gitea.io/en-us/config-cheat-sheet/#security-security

**Comment by anatbal** [comment]
Hi @marrobi , I have a few questions about the task:
1. Is the admin user that supposed to manage the gitea instance is the TRE administrator? or can it also be a TRE owner?
2. Will it be okay to have a static username for the gitea admin (e.g gitea_admin)? Since an admin user cannot be created with an env var, we will have to create it separately one the gitea container is up.
