### ISSUE TITLE
Ubuntu 18.04 LTS end of standard support is 31 May 2023

### ISSUE THREAD

**Issue by ciprianmaf** [microsoft/AzureTRE#3523]
Hello,

as **Nexus SS** and the **VMSS porter** are using **Ubuntu 18.04-LTS** and this OS reached the end of standard support, please upgrade to **Ubuntu 20.04 LTS** or **Ubuntu 22.04 LTS**, the latest operating systems.
Files:
/workspaces/cprd-tre/AzureTRE/templates/shared_services/sonatype-nexus-vm/terraform/vm.tf
/workspaces/cprd-tre/AzureTRE/core/terraform/resource_processor/vmss_porter/main.tf

Link: https://ubuntu.com/blog/18-04-end-of-standard-support

- [x] Nexus
- [x] Resource Processor
- [x] Guacamole VMs

**Comment by marrobi** [comment]
I've updated nexus in this PR - #3675

**Comment by SvenAelterman** [comment]
PR #3675 probably superseded by #3676

**Comment by SvenAelterman** [comment]
I have a working Ubuntu 20 DSVM. "Plain" Ubuntu still pending.

**Comment by SvenAelterman** [comment]
Oh, and I just realize that repo is private :(

**Comment by wojciechcloudkubed** [comment]
Hi @SvenAelterman, do You still have the repo sitting somewhere?

**Comment by SvenAelterman** [comment]
@wojciechcloudkubed Yes, I will invite you to it.

**Comment by tim-allen-ck** [comment]
Given the internet dependencies with the Ubuntu Data Science Vms, is it worth just adding some of the required packages to the cloud init scripts for the 22.04 and 20.04 base images?

**Comment by marrobi** [comment]
I'd support this, as most organisations build their own VM images. As long as we have the essentials on the scripts:

- Storage Explorer
- Docker
- Jupyter
- RStudio

Spring to mind. @SvenAelterman thoughts?

**Comment by marrobi** [comment]
@tim-allen-ck this might be good to look at: https://github.com/OxBRCInformatics/AzureTRE-Deployment/blob/main/vm-images/templates/linux/scripts/init_vm.sh

**Comment by Danny-Cooke-CK** [comment]
On the back of this it would be good to introduce a selectable "bootstrap" option.  so we can have 22.04 image with a standard bootstrap and then a data science vm bootstrap too.  Or something along those lines to add in some flexibility

**Comment by SvenAelterman** [comment]
@Danny-Cooke-CK When deploying, a different image template is selected. Based on that, I think the TF should be able to select a different vm_config script, if needed.

However, I am afraid if we have two different scripts, it will be harder to keep them in sync.

**Comment by SvenAelterman** [comment]
Sorry, I didn't fully catch up on the thread before I sent the response above. 

So, the suggestion then is instead of selecting an image (Ubuntu vs. DSVM) to select a bootstrap option when the user creates the deployment? I could see that working, yes.

Would we do something similar for Windows then?

What do we expect the maintenance overhead is for what's essentially building our own DSVM pipeline?

**Comment by tim-allen-ck** [comment]
I guess maintenance is minimal, just need to make sure we have the right packages added to the config script.

**Comment by marrobi** [comment]
In production we always recommend using custom VM images, rather than bootstrap scripts, as scripts are liable to hit transient issues and delay provisioning. As we can't publish a custom image as part of this repo we use bootstrap scripts. 

So I suggest we have one bootstrap script per user resource, install typical researcher tooling, similar to https://github.com/OxBRCInformatics/AzureTRE-Deployment/blob/main/vm-images/templates/linux/scripts/init_vm.sh, and leave the image selection facility (even if we only have one image - as then its easy to see how to add custom images - which should be documented too if not already).

Does that make sense?

**Comment by tim-allen-ck** [comment]
> In production we always recommend using custom VM images, rather than bootstrap scripts, as scripts are liable to hit transient issues and delay provisioning. As we can't publish a custom image as part of this repo we use bootstrap scripts.
> 
> So I suggest we have one bootstrap script per user resource, install typical researcher tooling, similar to https://github.com/OxBRCInformatics/AzureTRE-Deployment/blob/main/vm-images/templates/linux/scripts/init_vm.sh, and leave the image selection facility (even if we only have one image - as then its easy to see how to add custom images - which should be documented too if not already).
> 
> Does that make sense?

Sounds good to me. 
So we need a list of typical researcher tooling for the vms. 

- Storage Explorer
- Docker
- Jupyter
- RStudio

anything else?

**Comment by marrobi** [comment]
VSCode maybe, as long as enough to do some demos. The script from Oxford above looks like a good start.
