### ISSUE TITLE
Custom vm instructions

### ISSUE THREAD

**Issue by Danny-Cooke** [microsoft/AzureTRE#3603]
## Description

In my Azure TRE deployment I am trying to use custom vm's which I have built with extra software installed 
I'm struggling to deploy one using the readme instructions located here. https://github.com/microsoft/AzureTRE/blob/main/templates/workspace_services/guacamole/user_resources/README.md 

Are their any other places where I could understand this process better? I have the porter and template files edited and correct but the rest of the steps are confusing me a bit 

thanks in advance. Newbe tre user

**Comment by Danny-Cooke-cCK** [comment]
Hi @marrobi  no i didn't get it sorted in the end. 
I ended up having issues with the environment so had to rebuild. 
I closed the issue because there was no reply's and didn't want to leave it open whilst i was destroying / rebuilding. 

But as you have replied i hope you can help. 

i have 2 custom images in in our image gallary
i have created an environment variable in github referring to that gallary 
RP_BUNDLE_VALUES = 
{"image_gallery_id":"/subscriptions/<SUBSCRIPTION>/resourceGroups/<RG>/providers/Microsoft.Compute/galleries/GAL"}

i have Porter and the template updated with the new image details too. 

Is there anything else im missing before i try again? or does that sound correct so far?

**Comment by Danny-Cooke-cCK** [comment]
I have managed to do this now using this Previous issue as a guide. Perhaps the Quick start guide or the template readme could include these steps ? 

https://github.com/microsoft/AzureTRE/issues/3386
