### ISSUE TITLE
deployment Field of both work-spaces (unrestricted &   airlock import review workspace) 

### ISSUE THREAD

**Issue by brehmanepicsoft** [microsoft/AzureTRE#3701]
Remember to label the issue with the appropriate area, and also assign it to yourself if you plan to work on the issue in the near future.

****

**Steps to reproduce**

I deploy the base workspace multiple times, but when I attempt to deploy the unrestricted or airlock import review workspace,
I encounter an error stating that the operation has failed.
When the operation fails, it displays an error message indicating that authentication has not yet been provisioned for this resource.
There was a problem with the most recent deployment or update for this.

i use v0.14.1 version

**Comment by brehmanepicsoft** [comment]
<img width="729" alt="operation failed screen short" src="https://github.com/microsoft/AzureTRE/assets/142625590/03030bb3-4d32-4af7-8f0c-637f3ca964ed">

**Comment by marrobi** [comment]
@brehmanepicsoft can you get the operation logs from the workspace operations API? 

It might be a change in the base workspace in the latest release has caused an issue with the unrestricted workspace.

Actually looking at main, it is still running of v0.12.0 which means might be issues. This needs to be updated. Can you try making this change to 0.14.0, building and publishing the template with a new version and see if the issue is resolved?

https://github.com/microsoft/AzureTRE/blob/aff75331d132deeaf86caf406a830e6f38f8f54a/templates/workspaces/unrestricted/Dockerfile.tmpl#L12

**Comment by brehmanepicsoft** [comment]
"When I make modifications, execute all the necessary steps, and navigate to the Tree UI to initiate a new task, I encounter the following issue: 'Error retrieving workspace - Unable to decode or validate the token.'"

**Comment by brehmanepicsoft** [comment]
and finally i got the previous error .i change version in unrestricted and airlock from v 0.12.0 to v 0..14.0  
run the make all 
<img width="679" alt="operation failed" src="https://github.com/microsoft/AzureTRE/assets/142625590/c871595a-9dd2-4333-b159-d01fbd221ab0">
