### ISSUE TITLE
ReviewData folder show empty in review vm  airlock request

### ISSUE THREAD

**Issue by brehmanepicsoft** [microsoft/AzureTRE#3728]
when i create review vm after submitting request the vm create successfully but the review folder in vm is empty 
<img width="924" alt="empty" src="https://github.com/microsoft/AzureTRE/assets/142625590/e3b06721-af9e-461b-90d5-340c83496d46">
    

**Azure TRE release version (e.g. v0.14.0 or main):**

**Deployed Azure TRE components - click the (i) in the UI:**

**Comment by marrobi** [comment]
Can you access the files using the SAS token provided via the portal?

**Comment by marrobi** [comment]
Ok, I've just seen this elsewhere and the issue was a VM inside the workspace was being used for an import. For imports you need an import review workspace as per https://microsoft.github.io/AzureTRE/v0.14.1/tre-admins/configure-airlock-review/#configuring-airlock-vm-for-research-workspace

Closing this, feel free to reopen if this isn't the issue.
