### ISSUE TITLE
[BUG] Confusion between TRE Deployment SP and ResourceProcessor SP

### ISSUE THREAD

**Issue by limorl** [microsoft/AzureTRE#373]
**Describe the bug**
Quickstart.md indicates the ARM_SUBSCRIPTION_ID, ARM_TENANT_ID, ARM_CLIENT_ID and ARM_CLIENT_SECRET are optional and required only from deployment from CD or when deploying workspace.
However they are required also when running locally.

![image](https://user-images.githubusercontent.com/1086572/123336925-313ac580-d54f-11eb-9199-3ea2ed23de1b.png)

**Steps to reproduce**

1. Go to .devops/.env
2. Comment out ARM_SUBSCRIPTION_ID
3. run `make bootstrap`
4. Get the following error:
![image](https://user-images.githubusercontent.com/1086572/123326292-bcad5a00-d541-11eb-9f2d-0c3cae391243.png)
5. Do the same for the rest of the variables, and run make tre-deploy

**Comment by christoferlof** [comment]
It seems the Terraform related env variables (`ARM_*`) are injected into the CNABs by the processor function, why they are now required. We need to update the quickstart to flag them as required and also to describe what service principal(s) that are required.

**Comment by Lybecker** [comment]
The problem seems to be due to a mix-up of Service Principals. The solution uses two:

1. Owner SP to create the environment.
2. Contributor SP for the Resource Processor of the Composition Service to dynamically provision environments.

The first SP should be optional but is used by the Resource Processor function.

**Research**

The Resource Processor uses the SEC_ARM_CLIENT_* environment variables:
https://github.com/microsoft/AzureTRE/blob/e9c74900d2ac832199b52fcbecee5ef6f1aeb654/templates/core/terraform/processor_function/function.tf#L45-L46

As the CNAB_Builder cuts the _SEC_ section of the variable name before setting it for the ACI container
https://github.com/microsoft/AzureTRE/blob/e9c74900d2ac832199b52fcbecee5ef6f1aeb654/processor_function/shared/cnab_builder.py#L65

The values are set to the Owner SP here:
https://github.com/microsoft/AzureTRE/blob/e9c74900d2ac832199b52fcbecee5ef6f1aeb654/templates/core/terraform/main.tf#L129-L130

There is a problem with naming in the Terraform scripts - it would make it easier to read if they had names like OwnerSP/ContributorSP or ResourceProcessorSP... something along those lines

**Comment by limorl** [comment]
Here's a summary of our. discussion.
@marrobi and @Lybecker please confirm.

1. **For Quickstart**, we assume the Azure Admin is logged in with their credentials, hence they should avoid assigning SP to ARM_* variables. Therefore, the only required SP is for the ResourceProcessor with rbac role "Owner"

2. **For the CD**, both the ResourceProcessor SP and the ARM_* SP  - The latter is issued by the Azure Admin and has "Owner" rbac role.
