### ISSUE TITLE
E2E tests can leave test services in the TRE, instead of cleaning up properly

### ISSUE THREAD

**Issue by TonyWildish-BH** [microsoft/AzureTRE#3912]
**Describe the bug**
After manually deploying the TRE and running the E2E tests, I have a working TRE, but there is a workspace service named 'DO NOT USE' that's in the menu (see screenshot). The E2E tests should clean that up, regardless of success or failure of the test.

Unfortunately, I don't have the output of that run on disk, so I can't give more information than that.

**Steps to reproduce**

1. Deploy the TRE
1. Run the E2E tests
1. If you're (un)lucky, you'll find this vagrant service available to deploy.

**Azure TRE release version (e.g. v0.14.0 or main):**
main

**Deployed Azure TRE components - click the (i) in the UI:**
UI Version:   0.5.21
API Version: 0.18.5

<img width="630" alt="Screenshot 2024-04-26 at 9 39 18 AM" src="https://github.com/microsoft/AzureTRE/assets/153200306/ca02c2d8-65b0-469f-b9e4-563ac85ae865">

**Comment by marrobi** [comment]
Hi Tony, we run automated end to end tests to validate and environment in the development process. We typically don't log into these environments, but if it does fail, things need to stay as they are so we can troubleshoot what happened. We then destroy the whole environment, using another command (can read here if interested https://github.com/microsoft/AzureTRE/blob/main/maintainers.md#pr-comment-bot-commands )

E2E tests should not be part of production deployment. That's why we have this repo - https://github.com/microsoft/AzureTRE-Deployment

**Comment by TonyWildish-BH** [comment]
OK, thanks, we can close this one.
