### ISSUE TITLE
Unrestricted & Airlock Import Review workspace versions

### ISSUE THREAD

**Issue by jonnyry** [microsoft/AzureTRE#3941]
The Unrestricted  & Airlock Import Review workspaces reuse the terraform of the base workspace (so as not to unnecessarily duplicate the workspace terraform code)...

However it looks like the versions they are pulling are old, or at least out of sync with each other:

**Unrestricted workspace**
https://github.com/microsoft/AzureTRE/blob/main/templates/workspaces/unrestricted/Dockerfile.tmpl
TRE version = **0.14.0**

**Airlock Import Review**
https://github.com/microsoft/AzureTRE/blob/main/templates/workspaces/airlock-import-review/Dockerfile.tmpl
TRE version = **0.15.2**

**Additional question** - is it necessary to pull a versioned copy of the code from GitHub (and therefore risk being out of sync with the local copy)... rather than just copying the terraform locally from the ../base/terraform directory?

![image](https://github.com/microsoft/AzureTRE/assets/7916532/fe619f7b-2884-4104-bf60-ce12b15b9fa1)

**Comment by jonnyry** [comment]
Related https://github.com/microsoft/AzureTRE/issues/3658

**Comment by marrobi** [comment]
@jonnyry the reason it is pinned rather than using the local version we needed to run a script before build as the files are outside of the docker context. Also if you update base, it might break the others, and then have to update them in the same PR. This was getting messy.

We should look at porter dependencies maybe: https://porter.sh/docs/development/authoring-a-bundle/working-with-dependencies/# There was an issue with dynamic parameters, but this this now works.

As per #3658 could do with spiking some alternatives and deciding on a way forward.

**Comment by jonnyry** [comment]
Ok good to know - we have defined our own workspace so will bear that in mind.

**Comment by jonnyry** [comment]
Closing as duplicate
