### ISSUE TITLE
UI shows running costs for current month, not since workspace creation.

### ISSUE THREAD

**Issue by TonyWildish-BH** [microsoft/AzureTRE#4163]
The TRE UI displays costing information for the workspaces. I've just realised that our TRE is showing only the costs for the current month, not total cost since the workspace was created, so it's reset at the beginning of this month, for example.

Is that expected or desirable behaviour? I can see users getting confused by this.

**Comment by marrobi** [comment]
This is by design. Agree that could maybe be called out clearer, or be a config option. I believe the challenge is we can't get cost for the entire length of a project  - https://github.com/microsoft/AzureTRE/issues/2350.

If have a feature request for this behaviour to be changed then suggest create a new issue with a suggested approach.
