### ISSUE TITLE
As a TRE Administrator I want to delete the TRE environment

### ISSUE THREAD

**Issue by marrobi** [microsoft/AzureTRE#510]
## Description

As a TRE Administrator
I want to delete the TRE environment
So that I have no resources left behind on my Azure subscription or Azure Active Directory.

## Acceptance criteria

- [ ] make command removes the TRE 
- [ ] All azure resources are removed (or noted otherwise if purge protection prevents this)
- [ ] Azure diagnostic settings deleted.
- [ ] Can redeploy using the same tre_id
- [ ] Ability to delete just the TRE environment leaving management ACR and state store so no need to rebuild images. The reason you may want to leave the management RG needs to be documented.

## Implementation

- [x] #792
- [ ] Delete workspace resource groups based on naming convention
- [ ] Remove Azure diagnostics settings related to TRE in Azure Monitor
- [ ] ...

**Comment by christoferlof** [comment]
#792 related

**Comment by christoferlof** [comment]
`make tre-destroy` deletes all resources provisioned by `make tre-deploy`, leaving management resources (ACR, Storage) untouched.

**Comment by chboudry** [comment]
@marrobi additionnally it would be nice to select the type of deletion we want : by default Key Vault is soft delete enabled. So if we delete TRE workspace to make some tests and recreate it afterwards : it will fail because the KeyVault is going to restore itself and this will cause Terraform out of sync state.

Because of this to have a default delete option, and a "hard" delete option as well.
