### ISSUE TITLE
Guacamole does not get an image tag from resource processor 

### ISSUE THREAD

**Issue by anatbal** [microsoft/AzureTRE#848]
**Describe the bug**
When creating a new guacamole service, the tag is hard coded in the porter.yaml rather than dynamically transferred from the resource processor.

**Comment by marrobi** [comment]
This we need to give this some though. Given the bundle is for a fixed version, the image version used by that bundle may be better fixed too. 

What we will need to think about is how we ensure the guacamole image is built with the appropriate tag.

**Comment by eladiw** [comment]
Some more info for those taking this issue. when running 'make all' we can specify the to be used image tag. then services such as gitea use this value. however for Guacamole service there is a hard coded default value in the porter which will be used instead of this value. so in fact, if you deploy porter with a custom image such as 'build012' all the services will pick this tag image, but Guacamole won't
