### ISSUE TITLE
Validate no user session is created in the API

### ISSUE THREAD

**Issue by LizaShak** [microsoft/AzureTRE#982]
## Description

As a developer
I want to make sure no user session is created in the Management API
So that each API request is handled independently allowing the user to access it from different workspaces (different token audiences).

## Acceptance criteria

- [ ] #1001

**Comment by eladiw** [comment]
Verified. @TessFerrandez  @tamirkamara 

a. The Singleton is for the class itself, with the config values, meaning on each request the __call__ method is executed. so it is not a problem.
b. verified using the following flow:
* Created ws with a Guacamole service and with user resources (VMs)
* Gave this user 'researcher' permissions in the ws app registration
* Logged in to the Guacamole URL and was able to login to the VM
* Removed the role in AAD for that user (in the ws app registration)
* When using the SAME browser window we were still able to login to the VM (since the browser had a valid session)
* Opened an incognito window, the VMs were not visible, as expected.
